-- No admin seed in migration. Initial admin is created at application startup
-- by AdminBootstrapper (config/AdminBootstrapper.java), reading
-- INITIAL_ADMIN_USERNAME (default: admin) and INITIAL_ADMIN_PASSWORD env vars.
-- See docs/CREDENTIALS.md for first-deployment instructions.
--
-- If you have an existing dev environment that ran a prior version of this
-- migration (which seeded admin/admin123), the Flyway checksum will differ
-- after this change. Run `mvn flyway:repair` once to update the checksum.
-- Existing admin rows are preserved (AdminBootstrapper skips non-empty table).
